server:
  port: 8080
#  address: 172.18.61.117

spring:
    datasource:
        name: virtualTrade
        url: jdbc:mysql://120.79.34.242:3306/virtualTrade?useUnicode=true&characterEncoding=UTF-8
        username: vt_dev
        password: vt_dev__2018~*!#$
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml,classpath:mapping/ext/*.xml
  type-aliases-package: com.ooteco.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql